backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: images

collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Home Page
        name: index
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Main Quote
            name: mainQuote
            widget: string
          - label: Background Images
            name: backgrounds
            widget: list
            fields:
              - label: Image
                name: src
                widget: image
          - label: Content Squares
            name: squares
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: text
              - label: Image
                name: image
                widget: image
              - label: URL
                name: url
                widget: hidden
          - label: Quotes
            name: quotes
            widget: list
            fields:
              - label: Author
                name: author
                widget: string
              - label: Substring
                name: sub
                widget: string
              - label: Body
                name: body
                widget: text
      - file: src/pages/about.md
        label: About Page
        name: about
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Background Images
            name: backgrounds
            widget: list
            fields:
              - label: Image
                name: src
                widget: image
          - label: Body
            name: body
            widget: markdown
      - file: src/pages/am-i-eligible.md
        label: Am I Eligible Page
        name: am-i-eligible
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Background Images
            name: backgrounds
            widget: list
            fields:
              - label: Image
                name: src
                widget: image
          - label: Body
            name: body
            widget: markdown
      - file: src/pages/contact.md
        label: Contact Page
        name: contact
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Background Images
            name: backgrounds
            widget: list
            fields:
              - label: Image
                name: src
                widget: image
          - label: Body
            name: body
            widget: markdown
      - file: src/pages/depression.md
        label: Depression Page
        name: depression
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Background Images
            name: backgrounds
            widget: list
            fields:
              - label: Image
                name: src
                widget: image
          - label: Body
            name: body
            widget: markdown
      - file: src/pages/project.md
        label: Project Page
        name: project
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Background Images
            name: backgrounds
            widget: list
            fields:
              - label: Image
                name: src
                widget: image
          - label: Body
            name: body
            widget: markdown
      - file: src/pages/self-compassion.md
        label: Self-Compassion Page
        name: self-compassion
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Background Images
            name: backgrounds
            widget: list
            fields:
              - label: Image
                name: src
                widget: image
          - label: Body
            name: body
            widget: markdown
